export const FETCH_TEACHERPROFILE_BY_CATEGORY_SUBCATEGORY =
  "FETCH_TEACHERPROFILE_BY_CATEGORY_SUBCATEGORY";
export const FETCH_TEACHERPROFILE_BY_CATEGORY_SUBCATEGORY_FAIL =
  "FETCH_TEACHERPROFILE_BY_CATEGORY_SUBCATEGORY_FAIL";

export const FETCH_ALL_TEACHERPROFILE = "FETCH_ALL_TEACHERPROFILE";
export const FETCH_ALL_TEACHERPROFILE_FAIL = "FETCH_ALL_TEACHERPROFILE_FAIL";
